function opcode
{
  if [ $(echo | liquidsfz <(echo "<control>$1=0<region>$1=0") |& grep -c unsupported) != 2 ]; then
    echo "$1" | sed s/0/N/g
  fi
}

# opcode list generated from in sfzformat.github.io/opcodes
# ls | LC_COLLATE=C sort | sed 's/[A-Z]/0/g;s/.md$//g;s/^/opcode /g'
opcode amp_keycenter
opcode amp_keytrack
opcode amp_random
opcode amp_velcurve_0
opcode amp_veltrack
opcode ampeg_attack
opcode ampeg_attack_oncc0
opcode ampeg_attack_shape
opcode ampeg_attackcc0
opcode ampeg_decay
opcode ampeg_decay_shape
opcode ampeg_decay_zero
opcode ampeg_decaycc0
opcode ampeg_delay
opcode ampeg_delaycc0
opcode ampeg_depth
opcode ampeg_hold
opcode ampeg_holdcc0
opcode ampeg_release
opcode ampeg_release_shape
opcode ampeg_release_zero
opcode ampeg_releasecc0
opcode ampeg_start
opcode ampeg_startcc0
opcode ampeg_sustain
opcode ampeg_sustaincc0
opcode ampeg_vel2attack
opcode ampeg_vel2decay
opcode ampeg_vel2delay
opcode ampeg_vel2hold
opcode ampeg_vel2release
opcode ampeg_vel2sustain
opcode amplfo_delay
opcode amplfo_depth
opcode amplfo_depthcc0
opcode amplfo_depthchanaft
opcode amplfo_depthpolyaft
opcode amplfo_fade
opcode amplfo_freq
opcode amplfo_freqcc0
opcode amplfo_freqchanaft
opcode amplfo_freqpolyaft
opcode amplitude
opcode amplitude_curvecc0
opcode amplitude_oncc0
opcode amplitude_smoothcc0
opcode bend_down
opcode bend_smooth
opcode bend_step
opcode bend_stepdown
opcode bend_stepup
opcode bend_up
opcode count
opcode curve_index
opcode cutoff
opcode cutoff2
opcode cutoff2_curvecc0
opcode cutoff2_oncc0
opcode cutoff2_smoothcc0
opcode cutoff2_stepcc0
opcode cutoff_cc0
opcode cutoff_chanaft
opcode cutoff_curvecc0
opcode cutoff_oncc0
opcode cutoff_polyaft
opcode cutoff_smoothcc0
opcode cutoff_stepcc0
opcode default_path
opcode define
opcode delay
opcode delay_beats
opcode delay_cc0
opcode delay_oncc0
opcode delay_random
opcode delay_samples
opcode delay_samples_oncc0
opcode direction
opcode effect1
opcode effect2
opcode eg0_amplitude
opcode eg0_amplitude_oncc0
opcode eg0_bitred
opcode eg0_bitred_oncc0
opcode eg0_curve0
opcode eg0_cutoff
opcode eg0_cutoff2
opcode eg0_cutoff2_oncc0
opcode eg0_cutoff_oncc0
opcode eg0_decim
opcode eg0_decim_oncc0
opcode eg0_depth_lfo0
opcode eg0_depthadd_lfo0
opcode eg0_driveshape
opcode eg0_driveshape_oncc0
opcode eg0_eq0bw
opcode eg0_eq0bw_oncc0
opcode eg0_eq0freq
opcode eg0_eq0freq_oncc0
opcode eg0_eq0gain
opcode eg0_eq0gain_oncc0
opcode eg0_freq_lfo0
opcode eg0_level0
opcode eg0_level0_oncc0
opcode eg0_loop
opcode eg0_loop_count
opcode eg0_noiselevel
opcode eg0_noiselevel_oncc0
opcode eg0_noisestep
opcode eg0_noisestep_oncc0
opcode eg0_noisetone
opcode eg0_noisetone_oncc0
opcode eg0_pan
opcode eg0_pan_curve
opcode eg0_pan_curvecc0
opcode eg0_pan_oncc0
opcode eg0_pitch
opcode eg0_pitch_oncc0
opcode eg0_points
opcode eg0_rectify
opcode eg0_rectify_oncc0
opcode eg0_resonance
opcode eg0_resonance2
opcode eg0_resonance2_oncc0
opcode eg0_resonance_oncc0
opcode eg0_ringmod
opcode eg0_ringmod_oncc0
opcode eg0_shape0
opcode eg0_sustain
opcode eg0_time0
opcode eg0_time0_oncc0
opcode eg0_volume
opcode eg0_volume_oncc0
opcode eg0_width
opcode eg0_width_oncc0
opcode end
opcode eq0_bw
opcode eq0_bwcc0
opcode eq0_freq
opcode eq0_freqcc0
opcode eq0_gain
opcode eq0_gaincc0
opcode eq0_vel2freq
opcode eq0_vel2gain
opcode fil2_keycenter
opcode fil2_keytrack
opcode fil2_type
opcode fil2_veltrack
opcode fil_keycenter
opcode fil_keytrack
opcode fil_random
opcode fil_type
opcode fil_veltrack
opcode fileg_attack
opcode fileg_attack_shape
opcode fileg_decay
opcode fileg_decay_shape
opcode fileg_decay_zero
opcode fileg_delay
opcode fileg_depth
opcode fileg_hold
opcode fileg_release
opcode fileg_release_shape
opcode fileg_release_zero
opcode fileg_start
opcode fileg_sustain
opcode fileg_vel2attack
opcode fileg_vel2decay
opcode fileg_vel2delay
opcode fileg_vel2depth
opcode fileg_vel2hold
opcode fileg_vel2release
opcode fileg_vel2sustain
opcode fillfo_delay
opcode fillfo_depth
opcode fillfo_depthcc0
opcode fillfo_depthchanaft
opcode fillfo_depthpolyaft
opcode fillfo_fade
opcode fillfo_freq
opcode fillfo_freqcc0
opcode fillfo_freqchanaft
opcode fillfo_freqpolyaft
opcode gain_cc0
opcode gain_oncc0
opcode global_amplitude
opcode global_label
opcode global_volume
opcode group
opcode group_amplitude
opcode group_label
opcode group_volume
opcode hibend
opcode hibpm
opcode hicc0
opcode hichan
opcode hichanaft
opcode hihdcc0
opcode hikey
opcode hint_
opcode hipolyaft
opcode hiprog
opcode hirand
opcode hitimer
opcode hivel
opcode include
opcode key
opcode label_cc0
opcode lfo0_amplitude
opcode lfo0_amplitude_oncc0
opcode lfo0_amplitude_smoothcc0
opcode lfo0_amplitude_stepcc0
opcode lfo0_bitred
opcode lfo0_bitred_oncc0
opcode lfo0_bitred_smoothcc0
opcode lfo0_bitred_stepcc0
opcode lfo0_count
opcode lfo0_cutoff
opcode lfo0_cutoff2
opcode lfo0_cutoff2_oncc0
opcode lfo0_cutoff2_smoothcc0
opcode lfo0_cutoff2_stepcc0
opcode lfo0_cutoff_oncc0
opcode lfo0_cutoff_smoothcc0
opcode lfo0_cutoff_stepcc0
opcode lfo0_decim
opcode lfo0_decim_oncc0
opcode lfo0_decim_smoothcc0
opcode lfo0_decim_stepcc0
opcode lfo0_delay
opcode lfo0_delay_oncc0
opcode lfo0_depth_lfo0
opcode lfo0_depthadd_lfo0
opcode lfo0_drive
opcode lfo0_drive_oncc0
opcode lfo0_drive_smoothcc0
opcode lfo0_drive_stepcc0
opcode lfo0_eq0bw
opcode lfo0_eq0bw_oncc0
opcode lfo0_eq0bw_smoothcc0
opcode lfo0_eq0bw_stepcc0
opcode lfo0_eq0freq
opcode lfo0_eq0freq_oncc0
opcode lfo0_eq0freq_smoothcc0
opcode lfo0_eq0freq_stepcc0
opcode lfo0_eq0gain
opcode lfo0_eq0gain_oncc0
opcode lfo0_eq0gain_smoothcc0
opcode lfo0_eq0gain_stepcc0
opcode lfo0_fade
opcode lfo0_fade_oncc0
opcode lfo0_freq
opcode lfo0_freq_lfo0
opcode lfo0_freq_oncc0
opcode lfo0_freq_smoothcc0
opcode lfo0_freq_stepcc0
opcode lfo0_noiselevel
opcode lfo0_noiselevel_oncc0
opcode lfo0_noiselevel_smoothcc0
opcode lfo0_noiselevel_stepcc0
opcode lfo0_noisestep
opcode lfo0_noisestep_oncc0
opcode lfo0_noisestep_smoothcc0
opcode lfo0_noisestep_stepcc0
opcode lfo0_noisetone
opcode lfo0_noisetone_oncc0
opcode lfo0_noisetone_smoothcc0
opcode lfo0_noisetone_stepcc0
opcode lfo0_offset0
opcode lfo0_pan
opcode lfo0_pan_oncc0
opcode lfo0_pan_smoothcc0
opcode lfo0_pan_stepcc0
opcode lfo0_phase
opcode lfo0_phase_oncc0
opcode lfo0_pitch
opcode lfo0_pitch_oncc0
opcode lfo0_pitch_smoothcc0
opcode lfo0_pitch_stepcc0
opcode lfo0_ratio
opcode lfo0_resonance
opcode lfo0_resonance2
opcode lfo0_resonance2_oncc0
opcode lfo0_resonance2_smoothcc0
opcode lfo0_resonance2_stepcc0
opcode lfo0_resonance_oncc0
opcode lfo0_resonance_smoothcc0
opcode lfo0_resonance_stepcc0
opcode lfo0_scale
opcode lfo0_smooth
opcode lfo0_smooth_oncc0
opcode lfo0_step0
opcode lfo0_steps
opcode lfo0_volume
opcode lfo0_volume_oncc0
opcode lfo0_volume_smoothcc0
opcode lfo0_volume_stepcc0
opcode lfo0_wave
opcode lfo0_wave2
opcode lfo0_wave_oncc0
opcode lfo0_width
opcode lfo0_width_oncc0
opcode lfo0_width_smoothcc0
opcode lfo0_width_stepcc0
opcode lobend
opcode lobpm
opcode locc0
opcode lochan
opcode lochanaft
opcode lohdcc0
opcode lokey
opcode loop_count
opcode loop_crossfade
opcode loop_end
opcode loop_mode
opcode loop_start
opcode loop_type
opcode lopolyaft
opcode loprog
opcode lorand
opcode lotimer
opcode lovel
opcode master_amplitude
opcode master_label
opcode master_volume
opcode md5
opcode noise_filter
opcode noise_level
opcode noise_level_oncc0
opcode noise_level_smoothcc0
opcode noise_step
opcode noise_step_oncc0
opcode noise_stereo
opcode noise_tone
opcode noise_tone_oncc0
opcode note_offset
opcode note_polyphony
opcode note_selfmask
opcode octave_offset
opcode off_by
opcode off_curve
opcode off_mode
opcode off_shape
opcode off_time
opcode offset
opcode offset_cc0
opcode offset_oncc0
opcode offset_random
opcode on_hicc0
opcode on_locc0
opcode output
opcode pan
opcode pan_curvecc0
opcode pan_keycenter
opcode pan_keytrack
opcode pan_law
opcode pan_oncc0
opcode pan_smoothcc0
opcode pan_stepcc0
opcode pan_veltrack
opcode param_offset
opcode phase
opcode pitch
opcode pitch_curvecc0
opcode pitch_keycenter
opcode pitch_keytrack
opcode pitch_oncc0
opcode pitch_random
opcode pitch_smoothcc0
opcode pitch_stepcc0
opcode pitch_veltrack
opcode pitcheg_attack
opcode pitcheg_attack_shape
opcode pitcheg_decay
opcode pitcheg_decay_shape
opcode pitcheg_decay_zero
opcode pitcheg_delay
opcode pitcheg_depth
opcode pitcheg_hold
opcode pitcheg_release
opcode pitcheg_release_shape
opcode pitcheg_release_zero
opcode pitcheg_start
opcode pitcheg_sustain
opcode pitcheg_vel2attack
opcode pitcheg_vel2decay
opcode pitcheg_vel2delay
opcode pitcheg_vel2depth
opcode pitcheg_vel2hold
opcode pitcheg_vel2release
opcode pitcheg_vel2sustain
opcode pitchlfo_delay
opcode pitchlfo_depth
opcode pitchlfo_depthcc0
opcode pitchlfo_depthchanaft
opcode pitchlfo_depthpolyaft
opcode pitchlfo_fade
opcode pitchlfo_freq
opcode pitchlfo_freqcc0
opcode pitchlfo_freqchanaft
opcode pitchlfo_freqpolyaft
opcode polyphony
opcode polyphony_group
opcode position
opcode region_label
opcode resonance
opcode resonance2
opcode resonance2_curvecc0
opcode resonance2_oncc0
opcode resonance2_smoothcc0
opcode resonance2_stepcc0
opcode resonance_curvecc0
opcode resonance_oncc0
opcode resonance_smoothcc0
opcode resonance_stepcc0
opcode reverse_hicc0
opcode reverse_locc0
opcode rt_dead
opcode rt_decay
opcode sample
opcode script
opcode seq_length
opcode seq_position
opcode set_cc0
opcode set_hdcc0
opcode sostenuto_cc
opcode sostenuto_lo
opcode sostenuto_sw
opcode start_hicc0
opcode start_locc0
opcode stop_beats
opcode stop_hicc0
opcode stop_locc0
opcode sustain_cc
opcode sustain_lo
opcode sustain_sw
opcode sw_default
opcode sw_down
opcode sw_hikey
opcode sw_hilast
opcode sw_label
opcode sw_last
opcode sw_lokey
opcode sw_lolast
opcode sw_note_offset
opcode sw_octave_offset
opcode sw_previous
opcode sw_up
opcode sw_vel
opcode sync_beats
opcode sync_offset
opcode transpose
opcode trigger
opcode tune
opcode tune_curvecc0
opcode tune_oncc0
opcode tune_smoothcc0
opcode tune_stepcc0
opcode v0
opcode var00_curvecc0
opcode var00_mod
opcode var00_oncc0
opcode var00_target
opcode vendor_specific
opcode volume
opcode volume_curvecc0
opcode volume_oncc0
opcode volume_smoothcc0
opcode volume_stepcc0
opcode waveguide
opcode width
opcode width_curvecc0
opcode width_oncc0
opcode width_smoothcc0
opcode width_stepcc0
opcode xf_cccurve
opcode xf_keycurve
opcode xf_velcurve
opcode xfin_hicc0
opcode xfin_hikey
opcode xfin_hivel
opcode xfin_locc0
opcode xfin_lokey
opcode xfin_lovel
opcode xfout_hicc0
opcode xfout_hikey
opcode xfout_hivel
opcode xfout_locc0
opcode xfout_lokey
opcode xfout_lovel
